export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const SELECT_DROP_DOWN_DATA_RECEIVED =
  "EVENT/SELECT_DROP_DOWN_DATA_RECEIVED";
export const SELECTED_METRICS_RECEIVED = "EVENT/SELECTED_METRICS_RECEIVED";
export const METRIC_MEASUREMENTS_RECEIVED =
  "EVENT/METRIC_MEASUREMENTS_RECEIVED";
export const PAST_MEASUREMENTS_RECEIVED = "EVENT/PAST_MEASUREMENTS_RECEIVED";
